### ISSUE TITLE
'function' object is not subscriptable ERROR in Vsum.py

### ISSUE THREAD

**Issue by adityashukla17** [mayu-ot/vsum_dsf#1]
Kindly guide me through.
![screenshot 100](https://user-images.githubusercontent.com/37567037/39754457-e3cf2f38-52df-11e8-8033-b1d92f3f6ae8.png)

**Comment by mayu-ot** [comment]
Hello,
I set up the project from scratch, but could not reproduce the error.
Can you check the environment? The code is written in Python 2.7.

**Comment by adityashukla17** [comment]
I am also doing it from scratch, and I am using python 3.6. But as you are
suggesting, I will try using python 2.7. Will let you know if any help is
required.
Thank you :)

**Comment by adityashukla17** [comment]
This project is developed under Python 2.7 and it won't work with Python 3.6.
